services:
  portfolio-web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: portfolio-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    networks:
      - cloudfare-tunnel_default

networks:
  cloudfare-tunnel_default:
    external: true
