services:
  portfolio-web:
    image: ghcr.io/kore29/portfolio-web:latest
    container_name: portfolio-web
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    ports:
      - "${PORT_HOST:-3000}:${PORT:-3000}"
