services:
  portfolio-web:
    image: ghcr.io/kore29/portfolio-web:latest
    container_name: portfolio-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
    networks:
      - cloudfare-tunnel_default

  watchtower:
    image: containrrr/watchtower:latest
    container_name: portfolio-watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.40
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --cleanup --interval 300 portfolio-web

networks:
  cloudfare-tunnel_default:
    external: true
